#!/usr/bin/env python3
#
# ## addr(1) -- add to right
#
# [code](addr)
#
# ### SYNOPSIS
#
#     addr <text>
#
# ### Description
#
# Add str to right side of the input.
#
# ### Usage
#
#     $ echo abc | addr ABC
#     abcABC
#

import sys
import argparse
import fileinput
import re

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

parser.add_argument('text', type=str)

args = parser.parse_args()
del sys.argv[:]

ifs, ofs = utils.get_iofs(args)

# output
ifs_regex = re.compile('[%s]' % ifs) if ifs else ''

for line in fileinput.input():
    print("%s%s" % (line.strip(), args.text))
