#!/bin/bash
#
# ## crops(1) -- crop all matched patterns
#
# [code](crops)
#
# ### SYNOPSIS
#
#     crops <regex>
#
# ### Description
#
# Crop all the patterns which matches given string (regular expression).
# It includes all the patterns (from shortest to longest match).
#
# ### Usage
#
#     $ echo 1110100110 | crops "1.*1"
#     11
#     111
#     11101
#     1101
#     101
#     11101001
#     1101001
#     101001
#     1001
#     111010011
#     11010011
#     1010011
#     10011
#

cat - | ./stairr --fs="" | ./stairl --fs="" | grep -o "$1" | sort | uniq
