#!/usr/bin/env python3
#
# ## dupl(1) -- duplicate lines
#
# [code](dupl)
#
# ### SYNOPSIS
#
#     dupl <rows>
#
# ### Description
#
# Duplicate lines.
#
# ### Usage
#
#     $ echo A B C D | dupl 3
#     A B C D
#     A B C D
#     A B C D
#

import sys
import argparse
import fileinput
import re

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

parser.add_argument(
    'rows', type=int,
    help='number of rows')

args = parser.parse_args()
del sys.argv[:]

ifs = utils.get_ifs(args)
ofs = utils.get_ofs(args)

# output
ifs_regex = re.compile('[%s]' % ifs)

for line in fileinput.input():
    array = re.split(ifs_regex, line.strip())
    string = ofs.join(array)
    for i in range(0, args.rows):
        print(string)
    utils.write_eos(args)
