#!/usr/bin/env python3
#
# ## slit(1) -- slit
#
# [code](slit)
#
# ### SYNOPSIS
#
#     slit [--fs delim] rows
#
# ### Description
#
# Divide whole the inputs into given number of rows.
#
# ### Usage
#
#     # Print A to Z with 3 rows.
#     $ echo {A..Z} | slit 3
#     A B C D E F G H I
#     J K L M N O P Q R
#     S T U V W X Y Z
#
#     # Each line's number of field is adjusted to be near each other as much as possible.
#     $ echo A B C D | slit 3
#     A B
#     C
#     D
#

import sys
import argparse
import fileinput
import re
import math

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

parser.add_argument(
    'rows', type=int,
    help='number of rows')

args = parser.parse_args()
del sys.argv[:]

ifs = utils.get_ifs(args)
ofs = utils.get_ofs(args)

# output
array = []
delim_regex = re.compile('[%s]' % args.delimiter)

for line in fileinput.input():
    array.extend( re.split(delim_regex, line.strip()) )

for i in range(args.rows):
    cols = math.ceil(len(array) / (args.rows - i))
    print(' '.join(array[:cols]))
    del array[:cols]
