#!/usr/bin/env python3
#
# ## stairr(1) -- stairs from right side
#
# [code](stairr)
#
# ### SYNOPSIS
#
#     stairr [-h] [--fs delim] [--eos str]
#
# ### Description
#
# Generate sublist of the fields.
# Results match to the right side of the original input. In most cases, it looks stairs.
#
# ### Usage
#
#     $ echo A B C D | stairr
#     D
#     C D
#     B C D
#     A B C D
#

import sys
import argparse
import fileinput
import re

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

args = parser.parse_args()
del sys.argv[:]

ifs = utils.get_ifs(args)
ofs = utils.get_ofs(args)

# output
ifs_regex = re.compile('[%s]' % ifs)

for line in fileinput.input():
    array = re.split(ifs_regex, line.strip())
    for i in range(1, len(array) + 1):
        print(ofs.join(array[len(array)-i:]))
    utils.write_eos(args)
