#!/usr/bin/env python3
#
# ## stairl(1) -- stairs from left side
#
# [code](stairl)
#
# ### SYNOPSIS
#
#     stairl [--fs separator] [--eos str]
#
# ### Description
#
# Generate sublist of the fields. Each result matches to the left side of the original input.
# In most cases, it looks stairs.
#
# ### Usage
#
#     $ echo A B C D | stairl
#     A
#     A B
#     A B C
#     A B C D
#

import sys
import argparse
import fileinput
import re

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

args = parser.parse_args()
del sys.argv[:]

ifs, ofs = utils.get_iofs(args)

# output
ifs_regex = re.compile('[%s]' % ifs) if ifs else ''

for line in fileinput.input():
    array = utils.split(ifs_regex, line.strip())

    for i in range(1, len(array) + 1):
        print(ofs.join(array[:i]))
    utils.write_eos(args)
