#!/usr/bin/env python3
#
# ## stairr(1) -- stairs from right side
#
# [code](stairr)
#
# ### SYNOPSIS
#
#     stairr [-h] [--fs delim] [--eos str]
#
# ### Description
#
# Generate sublist of the fields.
# Results match to the right side of the original input. In most cases, it looks stairs.
#
# ### Usage
#
#     $ echo A B C D | stairr
#     D
#     C D
#     B C D
#     A B C D
#

import sys
import argparse
import fileinput
import signal
import re

# catch pipe close signal
def sigpipe_handler(e):
    sys.exit()

signal.signal(signal.SIGPIPE, sigpipe_handler)

# Parse args
parser = argparse.ArgumentParser()
parser.add_argument(
    '--fs', dest='delimiter', action='store', metavar='delim', default=' ',
    help='set delimiter')
parser.add_argument(
    '--eos', dest='eos', action='store', metavar='str', default=None,
    help='set result separator')

args = parser.parse_args()
del sys.argv[:]

# output
delim_regex = re.compile('[%s]' % args.delimiter)

for line in fileinput.input():
    array = re.split(delim_regex, line.strip())
    for i in range(1, len(array) + 1):
        print(' '.join(array[len(array)-i:]))
    if args.eos:
        print(args.eos)
