#!/usr/bin/env python3
#
# ## subset(1) -- list all subsets
#
# [code](subset)
#
# ### SYNOPSIS
#
#     subset
#
# ### Description
#
# Generate all the subsets of the fields.
#
# ### Usage
#
#     $ echo A B C D | subset
#     A
#     B
#     C
#     D
#     A B
#     A C
#     B C
#     A D
#     B D
#     C D
#     A B C
#     A B D
#     A C D
#     B C D
#     A B C D
#

import sys
import argparse
import fileinput
import signal
import re
import itertools

# catch pipe close signal
def sigpipe_handler(e):
    sys.exit()

signal.signal(signal.SIGPIPE, sigpipe_handler)

# Parse args
parser = argparse.ArgumentParser()
parser.add_argument(
    '--fs', dest='delimiter', action='store', metavar='delim', default=' ',
    help='set delimiter')

args = parser.parse_args()
del sys.argv[:]

# output
delim_regex = re.compile('[%s]' % args.delimiter)

for line in fileinput.input():
    array = re.split(delim_regex, line.strip())
    for i in range(1, len(array) + 1):
        for combination in itertools.combinations(array, i):
            print(' '.join(map(str, combination)))
