#!/usr/bin/env python3
#
# ## subset(1) -- list all subsets
#
# [code](subset)
#
# ### SYNOPSIS
#
#     subset
#
# ### Description
#
# Generate all the subsets of the fields.
#
# ### Usage
#
#     $ echo A B C D | subset
#     A
#     B
#     C
#     D
#     A B
#     A C
#     B C
#     A D
#     B D
#     C D
#     A B C
#     A B D
#     A C D
#     B C D
#     A B C D
#

import sys
import argparse
import fileinput
import signal
import re
import itertools

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

args = parser.parse_args()
del sys.argv[:]

ifs, ofs = utils.get_iofs(args)

# output
ifs_regex = re.compile('[%s]' % ifs) if ifs else ''

for line in fileinput.input():
    array = utils.split(ifs_regex, line.strip())
    for i in range(1, len(array) + 1):
        for combination in itertools.combinations(array, i):
            print(ofs.join(map(str, combination)))
