#!/usr/bin/env python3
#
# ## taker(1) -- take last n fields
#
# [code](taker)
#
# ### SYNOPSIS
#
#     taker <number>
#
# ### Description
#
# Print last N of fields.
#
# ### Usage
#
#     $ echo A B C D | taker 3
#     B C D
#

import sys
import argparse
import fileinput
import re

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

parser.add_argument('number', type=int)

args = parser.parse_args()
del sys.argv[:]

ifs, ofs = utils.get_iofs(args)

# output
ifs_regex = re.compile('[%s]' % ifs) if ifs else ''

for line in fileinput.input():
    array = utils.split(ifs_regex, line.strip())
    if args.number > len(array):
        sys.exit()
    print(ofs.join(array[len(array) - args.number:]))
