#!/usr/bin/env python3
#
# ## zcho(1) -- pyzact echo
#
# [code](zcho)
#
# ### SYNOPSIS
#
#     zcho
#
# ### Description
#
# Write arguments to the standard output.
#
# ### Usage
#
#     $ echo {A..Z} | zcho --ifs=" " --ofs=","
#     A,B,C,D
#

import sys
import argparse
import fileinput
import re
import math

sys.path.append('lib')
import utils

utils.exit_by_sigpipe()

# Parse args
parser = argparse.ArgumentParser()
utils.add_common_options(parser)

args = parser.parse_args()
del sys.argv[:]

ifs = utils.get_ifs(args)
ofs = utils.get_ofs(args)

# output
array = []
ifs_regex = re.compile('[%s]' % ifs) if ifs else ''

for line in fileinput.input():
    array = utils.split(ifs_regex, line.strip())
    print(ofs.join(array))
